In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr = arr+2
print(arr)
arr=arr*3
print(arr)
arr=arr/2s
print(arr)

[3 4 5 6 7]
[ 9 12 15 18 21]
[ 4.5  6.   7.5  9.  10.5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,6,4,5])
print(arr[::-1])

[5 4 6 3 2 1]


In [4]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_freq_value = np.bincount(x).argmax()
indices = np.where(x == most_freq_value)[0]

print(f'Most frequent value: {most_freq_value}')
print(f'Indices: {indices}')

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_freq_value_y = np.bincount(y).argmax()
indices_y = np.where(y == most_freq_value_y)[0]

print(f'Most frequent value: {most_freq_value_y}')
print(f'Indices: {indices_y}')

Most frequent value: 1
Indices: [0 5 7 8 9]
Most frequent value: 1
Indices: [0 1 2]


In [5]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
x = arr[0, 1]
print(f'Element at 1st row, 2nd column: {x}')
y = arr[2, 0]
print(f'Element at 3rd row, 1st column: {y}')

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [8]:
import numpy as np

your_name = np.linspace(10, 100, 25)
dimensions = your_name.ndim
shape = your_name.shape
total_ele = your_name.size
data_type = your_name.dtype
total_bytes = your_name.nbytes

print(f'Dimensions: {dimensions}')
print(f'Shape: {shape}')
print(f'Total elements: {total_ele}')
print(f'Data type: {data_type}')
print(f'Total bytes: {total_bytes} bytes')

transpose_array = your_name.reshape(25, 1)
print(f'Transpose using reshape(): \n{transpose_array}')

transpose_array_T = your_name.T
print(f'Transpose using T attribute: \n{transpose_array_T}')

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200 bytes
Transpose using reshape(): 
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute: 
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [9]:
import numpy as np

ucs420_your_name = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
mean_value = np.mean(ucs420_your_name)
median_value = np.median(ucs420_your_name)
max_value = np.max(ucs420_your_name)
min_value = np.min(ucs420_your_name)
unique_elements = np.unique(ucs420_your_name)

print(f'Mean: {mean_value}')
print(f'Median: {median_value}')
print(f'Max: {max_value}')
print(f'Min: {min_value}')
print(f'Unique elements: {unique_elements}')

reshaped_ucs420_your_name = ucs420_your_name.reshape(4, 3)
print(f'Reshaped array (4x3): \n{reshaped_ucs420_your_name}')

resized_ucs420_your_name = np.resize(ucs420_your_name, (2, 3))
print(f'Resized array (2x3): \n{resized_ucs420_your_name}')

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array (4x3): 
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array (2x3): 
[[10 20 30]
 [40 50 60]]
